// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';
import type { SupabaseClient } from '@supabase/supabase-js';

const DEFAULT_SUPABASE_URL = 'https://tzatuvxatsduuslxqdtm.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YXR1dnhhdHNkdXVzbHhxZHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5ODA0NzgsImV4cCI6MjA5MjU1NjQ3OH0.3Iknfd0YMTrz07YU_nb50m13QLkeioSo-f-DqKJwp3s';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// ── Lazy Supabase client ──────────────────────────────────────────
// The @supabase/supabase-js chunk (~203KB) is only loaded when
// getSupabase() is first called — NOT on initial page load.
// This keeps the main bundle lighter for users who only import files.

let _supabase: SupabaseClient<Database> | null = null;
let _initPromise: Promise<SupabaseClient<Database>> | null = null;

/**
 * Get the Supabase client, initializing it lazily on first call.
 * The @supabase/supabase-js library is dynamically imported only when needed.
 *
 * @returns Initialized SupabaseClient<Database>
 */
export async function getSupabase(): Promise<SupabaseClient<Database>> {
  if (_supabase) return _supabase;
  if (_initPromise) return _initPromise;

  _initPromise = (async () => {
    const { createClient } = await import('@supabase/supabase-js');
    _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
    return _supabase;
  })();

  return _initPromise;
}

/**
 * Synchronous accessor — returns the client if already initialized, null otherwise.
 * Use this to check if Supabase is available without triggering a load.
 */
export function getSupabaseSync(): SupabaseClient<Database> | null {
  return _supabase;
}
